Merge template version to v2

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -5,10 +5,17 @@ on:
     branches: [main]
   pull_request:
     branches: [main]
+  schedule:
+    - cron: "0 5 1,15 * *"
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 defaults:
   run:
-    shell: bash -e {0} # -e to fail on error
+    # to fail on error in multiline statements (-e), in pipes (-o pipefail), and on unset variables (-u).
+    shell: bash -euo pipefail {0}
 
 jobs:
   test:
@@ -17,64 +24,36 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python: ["3.10", "3.12"]
-        os: [ubuntu-latest]
-        # one that matches "project-name".lower().replace('-', '_'), one that doesn’t:
-        package-name: [scmorph]
+        include:
+          - os: ubuntu-latest
+            python: "3.10"
+          - os: ubuntu-latest
+            python: "3.12"
+          - os: ubuntu-latest
+            python: "3.12"
+            pip-flags: "--pre"
+            name: PRE-RELEASE DEPENDENCIES
+
+    name: ${{ matrix.name }} Python ${{ matrix.python }}
+
     env:
-      PROJECT_ROOT: .
+      OS: ${{ matrix.os }}
+      PYTHON: ${{ matrix.python }}
 
     steps:
-      # Setup
       - uses: actions/checkout@v4
-      - name: Set up Python ${{ matrix.python }}
-        uses: actions/setup-python@v5
         with:
-          python-version: ${{ matrix.python }}
-          cache: "pip"
-          cache-dependency-path: "**/pyproject.toml"
-      - name: Install Ubuntu system dependencies
-        if: matrix.os == 'ubuntu-latest'
-        run: sudo apt-get install pandoc
-      - name: Install build & check dependencies
-        run: python -m pip install --upgrade pip wheel cookiecutter pre-commit
-      # Check
-      - name: Set up pre-commit cache
-        uses: actions/cache@v3
+          filter: blob:none
+          fetch-depth: 0
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
         with:
-          path: ~/.cache/pre-commit
-          key: pre-commit-3|${{ matrix.python }}|${{ hashFiles(format('{0}/.pre-commit-config.yaml', env.PROJECT_ROOT)) }}
-      - name: Run pre-commit
-        run: |
-          cd "$PROJECT_ROOT"
-          git add .
-          pre-commit run --verbose --color=always --show-diff-on-failure --all-files
-      - name: Install the package
-        run: |
-          cd $PROJECT_ROOT
-          pip install ".[doc,test]"
-          python -c "import ${{ matrix.package-name }}"
-      # Docs
-      - name: Build the documentation
-        env:
-          SPHINXOPTS: --keep-going
-        run: |
-          cd "$PROJECT_ROOT/docs"
-          make html
-      - name: Test
+          cache-dependency-glob: pyproject.toml
+      - name: run tests using hatch
         env:
           MPLBACKEND: agg
           PLATFORM: ${{ matrix.os }}
           DISPLAY: :42
-        run: |
-          pytest --cov --cov-report=xml
-      - name: Report coverage
-        run: |
-          coverage report
+        run: uvx hatch test --cover --python ${{ matrix.python }}
       - name: Upload coverage
-        uses: codecov/codecov-action@v5
-        with:
-          name: codecov-umbrella # optional
-          verbose: true # optional (default = false)
-        env:
-          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+        uses: codecov/codecov-action@v4
